#!/usr/bin/lua

--! ### Example output generated by this script
--! PUTVAL somos-cto/uci-lime_ap_ssid/gauge-el-valle-reinicia N:0
--! ### (very hacky way to collect the community name, within collectd limitations)

local config = require("lime.config")
local libuci = require("uci")

local uci = libuci.cursor()

local hostname
uci:foreach("system", "system", function(s) hostname = uci:get("system", s[".name"], "hostname") end)

local ap_ssid = config.get("wifi", "ap_ssid")

print(
  "PUTVAL"..
  " "..hostname.."/uci-lime_ap_ssid/gauge-"..ap_ssid:gsub("[^%w-_]", "_")..
  " N:0"
)

uci:close()
