#!/usr/bin/lua

--! ### Example output generated by this script
--! PUTVAL somos-cto/randomstuff-linecount/gauge-babeld_hosts N:17
--! PUTVAL somos-cto/randomstuff-linecount/gauge-bat_hosts N:5

local config = require("lime.config")
local libuci = require("uci")

local uci = libuci.cursor()

local hostname
uci:foreach("system", "system", function(s) hostname = uci:get("system", s[".name"], "hostname") end)

local babeld_hosts = 0
for _ in io.lines('/tmp/babeld-hosts') do
  babeld_hosts = babeld_hosts + 1
end

print(
  "PUTVAL"..
  " "..hostname.."/randomstuff-linecount/gauge-babeld_hosts"..
  " N:"..babeld_hosts
)


local bat_hosts = 0
for _ in io.lines('/tmp/bat-hosts') do
  bat_hosts = bat_hosts + 1
end

print(
  "PUTVAL"..
  " "..hostname.."/randomstuff-linecount/gauge-bat_hosts"..
  " N:"..bat_hosts
)


local dhcp_hosts = 0
for _ in io.lines('/tmp/dhcp.hosts_remote') do
  dhcp_hosts = dhcp_hosts + 1
end

print(
  "PUTVAL"..
  " "..hostname.."/randomstuff-linecount/gauge-dhcp_hosts"..
  " N:"..dhcp_hosts
)

uci:close()
