#!/usr/bin/lua

--! ### Example output generated by this script
--! ###### host/measurement-instance/type-type_instance N:1234 ######
--! PUTVAL somos-cto/uci-lime_ap_ssid/gauge-el-valle-reinicia N:0
--! ### (very hacky way to collect the community name, within collectd limitations)

local config = require("lime.config")
local libuci = require("uci")

local uci = libuci.cursor()

local hostname
uci:foreach("system", "system", function(s) hostname = uci:get("system", s[".name"], "hostname") end)

local lat = uci:get("libremap", "location", "latitude")
local lon = uci:get("libremap", "location", "longitude")

print(
  "PUTVAL"..
  " "..hostname.."/uci-libremap_location/gauge-latitude"..
  " N:"..lat
)

print(
  "PUTVAL"..
  " "..hostname.."/uci-libremap_location/gauge-longitude"..
  " N:"..lon
)

uci:close()
